# -*- coding: utf-8 -*-
"""AIML_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9In44IJXHyLfHWuhuQPHBj6MlPAGyS4
"""

# Cancer Disease Detector
# Name: VAISHNAVI TIWARI
# Registration No.:25BAI10696
# Subject: Artificial Intelligence & Machine Learning
# Date: 28/03/2026

# importing all required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")

print("="*50)
print("   CANCER DISEASE DETECTOR")
print("="*50)

# -----------------------------------------------
# STEP 1 - Load the dataset
# -----------------------------------------------

# loading breast cancer dataset from sklearn
# this dataset has 569 samples and 30 features
data = load_breast_cancer()

# converting to dataframe using pandas
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
#This action was perforemed for easier manipulation.

# 0 = malignant (cancer)  1 = benign (no cancer)
print("\nDataset loaded successfully!")
print("Shape of dataset:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

print("\nChecking for null values:")
print(df.isnull().sum().sum(), "null values found")

print("\nClass distribution:")
print("Malignant (0):", (df['target'] == 0).sum())
print("Benign    (1):", (df['target'] == 1).sum())

# -----------------------------------------------
# STEP 2 - Splitting features and labels
# -----------------------------------------------

# X = input features,  y = output label
X = df.drop('target', axis=1)
y = df['target']

print("\nFeature matrix shape:", X.shape)
print("Label shape:", y.shape)

# splitting into training and testing data
# 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples :", X_test.shape[0])

# -----------------------------------------------
# STEP 3 - Feature Scaling
# -----------------------------------------------

# scaling the data so all features are in same range
# this helps the model learn better
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test  = sc.transform(X_test)

print("\nFeature scaling done!")

# -----------------------------------------------
# STEP 4 - Training the Model
# -----------------------------------------------

# using random forest classifier
# n_estimators = number of trees in the forest
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("\nModel training complete!")

# -----------------------------------------------
# STEP 5 - Predictions
# -----------------------------------------------

y_pred = model.predict(X_test)

# calculating accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\n" + "="*50)
print("MODEL RESULTS")
print("="*50)
print(f"Accuracy : {accuracy * 100:.2f}%")

# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)
print("\nTP =", cm[1][1], " FP =", cm[0][1])
print("TN =", cm[0][0], " FN =", cm[1][0])

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Malignant', 'Benign']))

# -----------------------------------------------
# STEP 6 - Testing on a new patient sample
# -----------------------------------------------

# taking one sample from test data and predicting
sample     = X_test[0].reshape(1, -1)
prediction = model.predict(sample)
probability = model.predict_proba(sample)

print("="*50)
print("SAMPLE PATIENT PREDICTION")
print("="*50)
if prediction[0] == 1:
    print("Result    : BENIGN (No Cancer Detected) ✓")
else:
    print("Result    : MALIGNANT (Cancer Detected) !")
print(f"Confidence: {max(probability[0]) * 100:.2f}%")

# -----------------------------------------------
# STEP 7 - Plotting graphs using matplotlib
# -----------------------------------------------

print("\nGenerating plots...")

fig, axes = plt.subplots(2, 2, figsize=(12, 10))
fig.suptitle('Cancer Disease Detector - Results', fontsize=14, fontweight='bold')

# --- Graph 1 : Confusion Matrix ---
ax1 = axes[0][0]
im = ax1.imshow(cm, cmap='Blues')
ax1.set_title('Confusion Matrix')
ax1.set_xlabel('Predicted')
ax1.set_ylabel('Actual')
ax1.set_xticks([0, 1])
ax1.set_yticks([0, 1])
ax1.set_xticklabels(['Malignant', 'Benign'])
ax1.set_yticklabels(['Malignant', 'Benign'])
# writing numbers inside boxes
for i in range(2):
    for j in range(2):
        ax1.text(j, i, str(cm[i][j]), ha='center', va='center',
                 fontsize=18, fontweight='bold', color='black')
plt.colorbar(im, ax=ax1)

# --- Graph 2 : Class Distribution Bar Chart ---
ax2 = axes[0][1]
classes     = ['Malignant', 'Benign']
class_count = [(df['target'] == 0).sum(), (df['target'] == 1).sum()]
colors      = ['#e74c3c', '#2ecc71']
bars = ax2.bar(classes, class_count, color=colors, edgecolor='black', width=0.4)
ax2.set_title('Class Distribution')
ax2.set_xlabel('Diagnosis')
ax2.set_ylabel('Number of Patients')
# adding count labels on top of bars
for bar, count in zip(bars, class_count):
    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 3,
             str(count), ha='center', fontsize=11, fontweight='bold')

# --- Graph 3 : Top 10 Important Features ---
ax3 = axes[1][0]
importances   = model.feature_importances_
feature_names = list(data.feature_names)
# sorting and picking top 10
top10       = sorted(zip(importances, feature_names), reverse=True)[:10]
top10_vals  = [x[0] for x in top10]
top10_names = [x[1] for x in top10]
ax3.barh(top10_names[::-1], top10_vals[::-1], color='steelblue', edgecolor='black')
ax3.set_title('Top 10 Important Features')
ax3.set_xlabel('Importance Score')

# --- Graph 4 : Accuracy Pie Chart ---
ax4 = axes[1][1]
correct   = int(accuracy * len(y_test))
incorrect = len(y_test) - correct
pie_labels = ['Correct', 'Incorrect']
pie_sizes  = [correct, incorrect]
pie_colors = ['#2ecc71', '#e74c3c']
ax4.pie(pie_sizes, labels=pie_labels, colors=pie_colors,
        autopct='%1.1f%%', startangle=90,
        wedgeprops={'edgecolor': 'black'})
ax4.set_title(f'Prediction Accuracy\n({accuracy*100:.2f}%)')

plt.tight_layout()
plt.savefig('cancer_detector_output.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nGraph saved as 'cancer_detector_output.png'")
print("\nProgram finished successfully!")
print("="*50)
